### ISSUE TITLE
MMCVModulatedDeformConv2d

### ISSUE THREAD

**Issue by Huangyouling** [yhwang-hub/dl_model_infer#20]
佬！在直接用trtexec 转换engine 中 MMCVModulatedDeformConv2d这个算子怎么解决呢？

**Comment by yhwang-hub** [comment]
mmcv中有这个算子的插件，具体位置可以通过如下方法确认：
`
import mmcv

mmcv.__ file __
`
你可以直接拷贝出来，然后单独编译插件生成对应的.so文件，在使用trtexec时通过--plugins 加载该插件的.so就可以了

**Comment by Huangyouling** [comment]
我试过源码编译tensorRT，把mmcv中的这个算子加进去一起编译，但是还是在转换时候还是找不到这个算子。按理说编译完成后的libplugin.so存在这个算子了吧
