### ISSUE TITLE
smoke onnx 导出报错

### ISSUE THREAD

**Issue by lDarryll** [yhwang-hub/dl_model_infer#8]
作者你好， 按照你smoke部署中的readme进行  onnx 导出:
修改内容：按要求注释了 `mmdet3d/models/dense_heads/smoke_mono3d_head.py` 中的代码

运行 `python smoke_pth2onnx.py` 遇到了如下错误：

```shell
Traceback (most recent call last):
  File "smoke_pth2onnx.py", line 3, in <module>
    from mmdet3d.apis import init_model
  File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/apis/inference.py", line 18, in <module>
    from mmdet3d.models import build_model
  File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/__init__.py", line 9, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/dense_heads/__init__.py", line 15, in <module>
    from .smoke_mono3d_head import SMOKEMono3DHead
ImportError: cannot import name 'SMOKEMono3DHead' from 'mmdet3d.models.dense_heads.smoke_mono3d_head' (/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/dense_heads/smoke_mono3d_head.py
```

如果不注释 `mmdet3d/models/dense_heads/smoke_mono3d_head.py` 中的代码，直接运行 `python smoke_pth2onnx.py` 可以导出onnx 但是在转engine是遇到如下错误：
```shell
attribute {
  name: "deform_groups"
  i: 1
  type: INT
}
attribute {
  name: "dilation"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "groups"
  i: 1
  type: INT
}
attribute {
  name: "padding"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "stride"
  ints: 1
  ints: 1
  type: INTS
}
domain: "mmcv"

[07/09/2023-17:39:16] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[07/09/2023-17:39:16] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[07/09/2023-17:39:16] [E] Failed to parse onnx file
[07/09/2023-17:39:16] [I] Finish parsing network model
[07/09/2023-17:39:16] [E] Parsing model failed
[07/09/2023-17:39:16] [E] Failed to create engine from model or file.
[07/09/2023-17:39:16] [E] Engine set up failed
```

望作者空闲时能帮忙答疑，感谢！

**Comment by yhwang-hub** [comment]
> 作者你好， 按照你smoke部署中的readme进行 onnx 导出: 修改内容：按要求注释了 `mmdet3d/models/dense_heads/smoke_mono3d_head.py` 中的代码
> 
> 运行 `python smoke_pth2onnx.py` 遇到了如下错误：
> 
> ```shell
> Traceback (most recent call last):
>   File "smoke_pth2onnx.py", line 3, in <module>
>     from mmdet3d.apis import init_model
>   File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
>     from .inference import (convert_SyncBN, inference_detector,
>   File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/apis/inference.py", line 18, in <module>
>     from mmdet3d.models import build_model
>   File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/__init__.py", line 9, in <module>
>     from .dense_heads import *  # noqa: F401,F403
>   File "/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/dense_heads/__init__.py", line 15, in <module>
>     from .smoke_mono3d_head import SMOKEMono3DHead
> ImportError: cannot import name 'SMOKEMono3DHead' from 'mmdet3d.models.dense_heads.smoke_mono3d_head' (/Data1/SS/works/smoke/wxz/mmdetection3d/mmdet3d/models/dense_heads/smoke_mono3d_head.py
> ```
> 
> 如果不注释 `mmdet3d/models/dense_heads/smoke_mono3d_head.py` 中的代码，直接运行 `python smoke_pth2onnx.py` 可以导出onnx 但是在转engine是遇到如下错误：
> 
> ```shell
> attribute {
>   name: "deform_groups"
>   i: 1
>   type: INT
> }
> attribute {
>   name: "dilation"
>   ints: 1
>   ints: 1
>   type: INTS
> }
> attribute {
>   name: "groups"
>   i: 1
>   type: INT
> }
> attribute {
>   name: "padding"
>   ints: 1
>   ints: 1
>   type: INTS
> }
> attribute {
>   name: "stride"
>   ints: 1
>   ints: 1
>   type: INTS
> }
> domain: "mmcv"
> 
> [07/09/2023-17:39:16] [E] [TRT] ModelImporter.cpp:776: --- End node ---
> [07/09/2023-17:39:16] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4890 In function importFallbackPluginImporter:
> [8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
> [07/09/2023-17:39:16] [E] Failed to parse onnx file
> [07/09/2023-17:39:16] [I] Finish parsing network model
> [07/09/2023-17:39:16] [E] Parsing model failed
> [07/09/2023-17:39:16] [E] Failed to create engine from model or file.
> [07/09/2023-17:39:16] [E] Engine set up failed
> ```
> 
> 望作者空闲时能帮忙答疑，感谢！

第一个问题建议检查下环境配置
第二个问题建议使用tensorrt8.5及以上版本
